Add regression tests for mrcal
Gold856/allwpilib pull request #13
Opened 2024-12-01 22:55 UTC by mcm001

2024-12-01 22:59 UTC, mcm001 commented
Not sure why CI just like isnt running at all

2024-12-01 23:00 UTC, Gold856 commented
Because you've never contributed before

2024-12-01 23:05 UTC, mcm001 commented
Im attempting to enable the google test plugin, hitting some fun gradle trouble though...

2024-12-02 22:45 UTC, mcm001 commented
Let me know when this should be rebased again and I'll go ahead and do that, and also add a couple more datasets just for sanity

2024-12-03 14:14 UTC, Gold856 commented
You'll need this patch to get tests compiling:
```diff
diff --git a/wpical/build.gradle b/wpical/build.gradle
index aa7ef7a18..1c71a66c5 100644
--- a/wpical/build.gradle
+++ b/wpical/build.gradle
@@ -20,8 +20,7 @@ ext {
     nativeName = 'wpical'
     useCpp = true
     sharedCvConfigs = [
-        apriltagDev : [],
-        apriltagTest: []]
+        wpicalTest: []]
     staticCvConfigs = []
 }
 
@@ -33,7 +32,6 @@ def wpilibVersionFileOutput = file("$buildDir/generated/main/cpp/WPILibVersion.c
 
 apply from: "${rootDir}/shared/ceres.gradle"
 apply from: "${rootDir}/shared/opencv.gradle"
-apply from: "${rootDir}/shared/googletest.gradle"
 
 task generateCppVersion() {
     description = 'Generates the wpilib version class'
@@ -189,8 +187,6 @@ model {
                         it.linker.args << '-lGL'
                     }
                 }
-
-                nativeUtils.useRequiredLibrary(it, 'opencv_shared');
             }
         }
     }
@@ -213,6 +209,25 @@ model {
                     }
                 }
             }
+            binaries.all {
+                if (it.targetPlatform.name == nativeUtils.wpi.platforms.roborio || it.targetPlatform.name.startsWith("linuxarm")) {
+                    it.buildable = false
+                    return
+                }
+                lib project: ':wpiutil', library: 'wpiutil', linkage: 'static'
+                lib project: ':wpigui', library: 'wpigui', linkage: 'static'
+                lib project: ':thirdparty:imgui_suite', library: 'imgui', linkage: 'static'
+                lib project: ':apriltag', library: 'apriltag', linkage: 'static'
+                nativeUtils.useRequiredLibrary(it, 'ceres')
+                nativeUtils.useRequiredLibrary(it, 'opencv_static')
+                it.cppCompiler.define 'GLOG_USE_GLOG_EXPORT'
+                if (it.targetPlatform.operatingSystem.isWindows()) {
+                    it.cppCompiler.define('GLOG_DEPRECATED', '__declspec(deprecated)')
+                } else {
+                    it.cppCompiler.define('GLOG_DEPRECATED', '[[deprecated]]')
+                }
+                lib project: ':thirdparty:googletest', library: 'googletest', linkage: 'static'
+            }
         }
     }
 }
```
There are a few warnings and build errors still when the tests are being built. Since the icon is broken and breaks the build, you'll have to replace the wpical icon with something like the SysId icon (you can commit it if you want and I can revert it on my own.)

2024-12-05 03:38 UTC, Gold856 requested changes

2024-12-05 03:38 UTC, Gold856 commented on wpical/build.gradle
> +        apriltagTest: []]
```suggestion
        wpicalTest: []]
```

2024-12-05 03:38 UTC, Gold856 commented on wpical/build.gradle
> +apply from: "${rootDir}/shared/googletest.gradle"
Remove
```suggestion
```

2024-12-05 03:38 UTC, Gold856 commented on wpical/build.gradle
> +            }
```suggestion
            }
            binaries.all {
                if (it.targetPlatform.name == nativeUtils.wpi.platforms.roborio || it.targetPlatform.name.startsWith("linuxarm")) {
                    it.buildable = false
                    return
                }
                lib project: ':wpiutil', library: 'wpiutil', linkage: 'static'
                lib project: ':wpigui', library: 'wpigui', linkage: 'static'
                lib project: ':thirdparty:imgui_suite', library: 'imgui', linkage: 'static'
                lib project: ':apriltag', library: 'apriltag', linkage: 'static'
                nativeUtils.useRequiredLibrary(it, 'ceres')
                nativeUtils.useRequiredLibrary(it, 'opencv_static')
                it.cppCompiler.define 'GLOG_USE_GLOG_EXPORT'
                if (it.targetPlatform.operatingSystem.isWindows()) {
                    it.cppCompiler.define('GLOG_DEPRECATED', '__declspec(deprecated)')
                } else {
                    it.cppCompiler.define('GLOG_DEPRECATED', '[[deprecated]]')
                }
                lib project: ':thirdparty:googletest', library: 'googletest', linkage: 'static'
            }
```

2024-12-05 05:04 UTC, merged